export const CATEGORIES = [
  "Weddings",
  "Portraits",
  "Family & Newborn",
  "Maternity",
  "Events",
  "Corporate & Headshots",
  "Boudoir",
  "Products",
  "Food",
  "Real Estate",
  "Architecture",
  "Fashion",
  "Automotive",
  "Drone & Aerial",
  "Sports",
  "Pets & Animals",
  "Concerts & Music",
  "Travel",
  "Nature & Landscape",
  "Street & Documentary",
  "Artistic & Fine Art",
] as const;

export type Category = (typeof CATEGORIES)[number];

// Maps canonical English DB value → Categories translation key
export const CATEGORY_KEY: Record<string, string> = {
  "Weddings":              "weddings",
  "Portraits":             "portraits",
  "Family & Newborn":      "family_newborn",
  "Maternity":             "maternity",
  "Events":                "events",
  "Corporate & Headshots": "corporate_headshots",
  "Boudoir":               "boudoir",
  "Products":              "products",
  "Food":                  "food",
  "Real Estate":           "real_estate",
  "Architecture":          "architecture",
  "Fashion":               "fashion",
  "Automotive":            "automotive",
  "Drone & Aerial":        "drone_aerial",
  "Sports":                "sports",
  "Pets & Animals":        "pets_animals",
  "Concerts & Music":      "concerts_music",
  "Travel":                "travel",
  "Nature & Landscape":    "nature_landscape",
  "Street & Documentary":  "street_documentary",
  "Artistic & Fine Art":   "artistic_fine_art",
};
